name: 'Update YAML'
author: Rick Meneely <rick@meneely.com>
branding:
  icon: edit
  color: purple
description: Update YAML file values
inputs:
  infile:
    description: The YAML file to be updated
    default: 'values.yaml'
    required: false
  varlist:
    description: Comma separated list of var=value
    default: ''
    required: false
outputs:
  updated:
    description: 'Set to True or False based on if the infile was modified'
    value: ${{ steps.update-yaml.outputs.updated }}
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - run: python update-yaml.py -i ${{ inputs.infile }} -V "${{ inputs.varlist }}" > .update-yaml.tmp
      shell: bash
    - run: mv .update-yaml.tmp ${{ inputs.infile }}
      shell: bash
